// client/components/LinkButton.tsx
import toast from "react-simple-toasts";
import { RiLink } from "react-icons/ri";

type urlProp = {
  url: string;
};

const copyToClipboard = async (url: string) => {
  await navigator.clipboard.writeText(url);
  toast("URL copied to clipboard.");
};

export default function Login(data: urlProp) {
  return (
    <>
      <button onClick={() => copyToClipboard(data.url)} title="copy URL">
        <RiLink />
      </button>
    </>
  );
}

// src/lib/LinkButton.svelte
<script lang="ts">
	import toast, { Toaster } from 'svelte-french-toast';
	import { LinkSolid } from 'flowbite-svelte-icons';

	export let url: string;

	const copyToClipboard = async (url: string) => {
		await navigator.clipboard.writeText(url);
		toast.success('URL copied to clipboard.');
	};
</script>

<Toaster />
<button class="px-2" on:click={() => copyToClipboard(url)} title="copy URL">
	<LinkSolid />
</button>
