// client/pages/articles/[id].tsx
import { ArticleContent } from "../../types/types";
import Link from "next/link";
import { useEffect, useState } from "react";
import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import {
  RiHeart2Line,
  RiHeart2Fill,
  RiInboxArchiveLine,
  RiInboxUnarchiveFill,
  RiDeleteBin2Line,
} from "react-icons/ri";
import { getArticleContent } from "../api/articles/[id]";
import Head from "next/head";
import Image from "next/image";
import Tags from "@/components/Tags";
import LinkButton from "@/components/LinkButton";
import { MINI_LOGO_SIZE } from "@/components/Header";
import { FooterImage } from "@/components/Footer";

type Data = ArticleContent;

interface Update {
  pos: number;
  prog: number;
  updated: boolean;
}

export const getServerSideProps: GetServerSideProps<{
  data: Data;
}> = async (context) => {
  if (context.params) {
    const id = context.params.id;
    const data = await getArticleContent(id as string);
    return { props: { data } };
  } else {
    return { props: { data: [] } };
  }
};

export default function Article({
  data,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  let currentPosition = 0;

  const [articleContent, setArticleContent] = useState<ArticleContent>(data);

  const getScrollPosition = (): Update => {
    const bodyheight = document.documentElement.scrollHeight;
    const scrolled = document.documentElement.scrollTop;
    const client = document.documentElement.clientHeight;
    const pos = Math.round((scrolled * 100) / bodyheight);
    const prog = Math.abs(bodyheight - client - scrolled);

    let updated = false;
    if (pos !== currentPosition) {
      console.debug(pos);
      console.debug(currentPosition);
      currentPosition = pos;
      updated = true;
    }

    if (prog < 1) {
      return { pos: pos, prog: 100, updated: updated };
    } else {
      return {
        pos: pos,
        prog: 100 - Math.round((prog * 100) / bodyheight),
        updated: updated,
      };
    }
  };

  const saveScrollPos = () => {
    const updated = getScrollPosition();
    if (updated.pos !== 0 && updated.updated) {
      fetch(
        `/api/articles/${articleContent.id}?pos=${updated.pos}&prog=${updated.prog}`,
        {
          method: "POST",
        }
      ).then((res) => {
        if (!res.ok) {
          console.error("Cannot update progress.");
        }
      });
    }
  };

  const restoreScrollPos = () => {
    const scroll = Math.round(
      (document.documentElement.scrollHeight * articleContent.position) / 100
    );
    globalThis.scrollTo(0, scroll);
  };

  useEffect(() => {
    let mounted = true;
    if (mounted) {
      restoreScrollPos();
    }
    return () => {
      mounted = false;
    };
  }, []);

  useEffect(() => {
    const interval = setInterval(() => {
      saveScrollPos();
    }, 2000);

    return () => clearInterval(interval);
  }, []);

  const toggleLiked = async () => {
    const res = await fetch(`/api/articles/${articleContent.id}?toggle=liked`, {
      method: "POST",
      body: articleContent.id,
    });
    if (!res.ok) {
      console.error("Cannot toggle like.");
    } else {
      setArticleContent((x) => ({
        ...x,
        liked: !x.liked,
      }));
    }
  };

  const toggleArchived = async () => {
    const res = await fetch(
      `/api/articles/${articleContent.id}?toggle=archived`,
      {
        method: "POST",
        body: articleContent.id,
      }
    );
    if (!res.ok) {
      console.error("Cannot archive article.");
    } else {
      setArticleContent((x) => ({
        ...x,
        archived: !x.archived,
      }));
    }
  };

  const deleteArticleItself = async () => {
    const res = await fetch(`/api/articles/${articleContent.id}`, {
      method: "DELETE",
    });
    if (!res.ok) {
      console.error("Cannot delete article.");
    } else {
      globalThis.location.href = "/";
    }
  };

  if (!articleContent) {
    return <h1>No article found.</h1>;
  }

  // Already sanitized on server side
  const create_markup = () => {
    return { __html: articleContent.html };
  };

  const Buttons = ({ data }: { data: ArticleContent }) => {
    return (
      <div className="flex">
        <LinkButton url={articleContent.url} />
        <button className="px-2" onClick={toggleLiked} title="toggle liked">
          {data.liked ? <RiHeart2Fill /> : <RiHeart2Line />}
        </button>
        <button
          className="px-2"
          onClick={toggleArchived}
          title="toggle archived"
        >
          {data.archived ? <RiInboxUnarchiveFill /> : <RiInboxArchiveLine />}
        </button>
        <button className="px-2" onClick={deleteArticleItself} title="delete">
          <RiDeleteBin2Line />
        </button>
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>
          {articleContent.title} | {process.env.NEXT_PUBLIC_TITLE}
        </title>
      </Head>
      <div className="flex items-center bg-gray-900 sticky top-0 my-3">
        <Link href="/">
          <Image
            src={"/logo_dark.png"}
            alt="leaf"
            height={MINI_LOGO_SIZE}
            width={MINI_LOGO_SIZE}
          />
        </Link>
        <div className="ml-auto">
          <Buttons data={articleContent} />
        </div>
      </div>
      <div className="text-lg text-center leading-6 w-3/4 m-auto">
        {articleContent.title}
      </div>
      <div className="text-sm text-gray-400 line-clamp-1 my-3 w-2/3 m-auto">
        <a href={articleContent.url}>{articleContent.url}</a>
      </div>
      <div className="mb-6">
        <div dangerouslySetInnerHTML={create_markup()} />
      </div>
      <hr className="border-2 rounded-md my-5" />
      <div className="article-tags">
        <Tags tags={articleContent.tags} id={articleContent.id} />
      </div>
      <FooterImage />
    </>
  );
}

// src/routes/article/[id]/+page.svelte
<script lang="ts">
	import Tags from '$lib/Tags.svelte';
	import { Action } from '$lib/types';
	import { onMount, tick } from 'svelte';
	import type { PageData } from './$types';

	export let data: PageData;

	const getScrollPosition = () => {
		const bodyheight = document.documentElement.scrollHeight;
		const scrolled = document.documentElement.scrollTop;
		const client = document.documentElement.clientHeight;
		const pos = Math.round((scrolled * 100) / bodyheight);
		const prog = Math.abs(bodyheight - client - scrolled);

		if (prog < 1) {
			return { pos: pos, prog: 100 };
		} else {
			return {
				pos: pos,
				prog: 100 - Math.round((prog * 100) / bodyheight)
			};
		}
	};

	const saveScrollPos = () => {
		const updated = getScrollPosition();
		fetch(`/api/article`, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json'
			},
			body: JSON.stringify({
				id: data.id,
				action: Action.UpdatePosition,
				pos: updated.pos,
				prog: updated.prog
			})
		}).then((res) => {
			if (!res.ok) {
				console.error('Cannot update progress.');
			}
		});
	};

	const restoreScrollPos = () => {
		if (data.result?.position) {
			console.log(data.result.position);
			const scroll = Math.round(
				(document.documentElement.scrollHeight * data.result.position) / 100
			);
			setTimeout(() => {
				window.scrollTo(0, scroll);
			}, 0);
		}
	};

	onMount(async () => {
		restoreScrollPos();
	});
</script>

<svelte:window on:scroll={saveScrollPos} />
{#if data.result}
	<div class="sticky top-0 my-3 flex h-8 items-center border-b bg-slate-50">
		<a href="/"> Home </a>
		<div class="ml-auto">buttons</div>
	</div>
	<div class="m-auto w-3/4 text-center text-lg font-semibold leading-6">
		{data.result.title}
	</div>
	<div class="mx-3 mb-6 mt-3 line-clamp-1 text-center text-sm text-gray-400">
		<a href={data.result.url}>{data.result.url}</a>
	</div>
	<div class="mb-6">
		<!-- eslint-disable -->
		{@html data.result.html}
	</div>
	footer
	<div class="mx-3 mb-6">
		<Tags tags={data.result.tags} id={data.id} />
	</div>
{:else}
	<h1>Failed to read article id {data.id}.</h1>
{/if}
