// components/Header.tsx
export const Header = () => {
  return (
    <>
      <div className="header">
        <li>
          <ul>
            <a href="/">acidpaper</a>
          </ul>
          <form action="/api/create" method="POST">
            <input name="url" type="URL" />
            <button type="submit">Add</button>
          </form>
          <ul>
            <form action="/search" method="GET">
              <input type="text" id="query" name="q" />
              <button type="submit">Search</button>
            </form>
          </ul>
          <ul>
            <a href="/archived">archived</a>
          </ul>
          <ul>
            <a href="/liked">liked</a>
          </ul>
        </li>
      </div>
    </>
  );
};

// frontend/src/Header.tsx
import type { Component } from "solid-js";

const Header: Component = () => {
  return (
    <div class="header">
      <script defer type="text/javascript" src="/static/index.js"></script>

      <div id="acidpaper">acidpaper</div>
      <form action="" method="post" id="add">
        <div>
          <input type="url" id="url" />
          <button type="button">add</button>
        </div>
      </form>
    </div>
  );
};

export default Header;
