// react/src/Header.tsx
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useRecoilState } from "recoil";
import { listState } from "./contexts/atoms";

const Header = () => {
  const [list, setList] = useRecoilState(listState);
  const [url, setUrl] = useState("");
  const [query, setQuery] = useState("");

  const add_url = (event) => {
    event?.preventDefault();
    setUrl(
      () => (document.getElementById("url")! as HTMLTextAreaElement).value
    );
    console.log(url);
    fetch("http://localhost:8000/a", {
      method: "POST",
      body: url,
    }).then((res) =>
      !res.ok ? console.log("Error: Cannot add url.") : console.log("Added.")
    );
    setUrl(() => "");
    fetch("http://localhost:8000/")
      .then((res) => res.json())
      .then((j) => setList(j));
  };

  const send_query = async () => {
    setQuery(
      () => (document.getElementById("query")! as HTMLTextAreaElement).value
    );
    const target = "http://localhost:3000/s?q=" + query;
    location.href = target;
  };

  return (
    <>
      <ul className="header">
        <li id="acidpaper">
          <Link to="/">acidpaper</Link>
        </li>
        <li id="add">
          <form onSubmit={add_url}>
            <input
              type="text"
              id="url"
              onChange={(e) => setUrl(() => e.target.value)}
              placeholder="Add"
            />
          </form>
        </li>
        <li id="search">
          <form onSubmit={() => send_query()}>
            <input type="text" id="query" value={query} placeholder="Search" />
          </form>
        </li>
        <li>
          <Link to="archive">archived</Link>
        </li>
      </ul>
    </>
  );
};

export default Header;

// frontend/src/Header.tsx
import { Component, createResource, createSignal } from "solid-js";
import { setList } from "./Lists";

const Header: Component = () => {
  const add_url = async () => {
    const res = await fetch("http://localhost:8000/a", {
      method: "POST",
      body: url(),
    });
    if (!res.ok) {
      console.log("Error: Cannot add url.");
    }
    setUrl(() => "");
    const updated = await fetch("http://localhost:8000/");
    setList(await updated.json());
  };

  const send_query = async () => {
    setQuery(
      () => (document.getElementById("query")! as HTMLTextAreaElement).value
    );
    const target = "http://localhost:8000/s?q=" + query();
    console.log(target);
    const matched = await fetch(target);
    if (!matched.ok) {
      console.log("Error: Cannot search documents.");
    }
    setList(await matched.json());
    setQuery(() => "");
  };

  const [url, setUrl] = createSignal("");
  const [_loading] = createResource(url, add_url);

  const [query, setQuery] = createSignal("");

  return (
    <div class="header">
      <div id="acidpaper">acidpaper</div>
      <div id="add">
        <input type="text" id="url" value={url()} />
        <button
          onClick={() =>
            setUrl(
              () =>
                (document.getElementById("url")! as HTMLTextAreaElement).value
            )
          }
        >
          add
        </button>
      </div>
      <div id="search">
        <input type="text" id="query" value={query()} />
        <button onClick={() => send_query()}>search</button>
      </div>
    </div>
  );
};

export default Header;
